-----------------------------------------------------------------------
-- Config
-----------------------------------------------------------------------
local _, cf = ...

cf.Config = {
	["Enabled"] = true, --Enable the ChatFilter. // 是否开启本插件

	["noprofanityFilter"] = true, --Disable the profanityFilter. // 关闭语言过滤器
	["nowhisperSticky"] = true, --Disable the sticky of Whisper. // 取消持续密语
	["noaltArrowkey"] = true, --Disable the AltArrowKeyMode. // 取消按住ALT才能移动光标
	["nojoinleaveChannel"] = true, --Disable the alert joinleaveChannel. // 关闭进出频道提示

	["MergeTalentSpec"] = true, --Merge the messages:"You have learned/unlearned..." // 当切换天赋后合并显示“你学会了/忘却了法术…”
	["FilterPetTalentSpec"] = true, --Filter the messages:"Your pet has learned/unlearned..." // 不显示“你的宠物学会了/忘却了…”

	["MergeAchievement"] = true, --Merge the messages:"...has earned the achievement..." // 合并显示获得成就
	["MergeManufacturing"] = true, --Merge the messages:"You has created..." // 合并显示“你制造了…”

	["FilterRaidAlert"] = true, --Filter the bullshit messages from RaidAlert. // 过滤煞笔RaidAlert的脑残信息
	["FilterQuestReport"] = true, --Filter the bullshit messages from QuestReport. // 过滤掉烦人的任务通报信息

	["FilterDuelMSG"] = true, --Filter the messages:"... has defeated/fled from ... in a duel." // 过滤“...在决斗中战胜了...”
	["FilterDrunkMSG"] = true, --Filter the drunk messages:"... has drunked ..."// 过滤“...喝醉了.”
	["FilterAuctionMSG"] = true, --Filter the messages:"Auction created/cancelled."// 过滤“已开始拍卖/拍卖取消.”

	["FilterAdvertising"] = true, --Filter the advertising messages. // 过滤广告信息
	["AllowMatchs"] = 2, --How many words can be allowd to use. // 允许的关键字配对个数
	["IgnoreAdTimes"] = 60, --How many times shall we shield the advertising. // 屏蔽发广告的玩家多长时间(分钟)
	["IgnoreMore"] = true, --When the ignorelist is full, you can still ignore players. // 当屏蔽列表满了后仍然可以屏蔽玩家

	["FilterMultiLine"] = true, --Filter the multiple messages. // 过滤多行信息
	["AllowLines"] = 3, --How many lines can be allowd. // 允许的最大行数

	["FilterRepeat"] = true, --Filter the repeat messages. // 过滤重复聊天信息
	["RepeatAlike"] = 75, --Set the similarity between the messages. // 设定重复信息相似度
	["RepeatInterval"] = 120, --Set the interval between the messages. // 设定重复信息间隔时间(秒)

	["FilterByLevel"] = false, --Filter the messages by level. // 屏蔽小号发言
	["OnlyOnWhisper"] = nil, --Only filter the whisper messages. // 只过滤密语
	["AllowLevel"] = 10, --Filter the messages by level. // 屏蔽多少级以下的发言

	["Debug"] = nil,

	["SafeWords"] = {
		"recruit",
		"dkp",
		"looking",
		"lf[gm]",
		"|cff",
		"raid",
		"recount",
		"skada",
		"boss",
		"dps",
	},
	["DangerWords"] = {
		"①",
		"②",
		"③",
		"④",
		"⑤",
		"⑥",
		"⑦",
		"⑧",
		"⑨",
		"⒈",
		"⒉",
		"⒊",
		"⒋",
		"⒌",
		"⒍",
		"⒎",
		"⒏",
		"⒐",
		"⒑",
		"㈠",
		"㈡",
		"㈢",
		"㈣",
		"㈤",
		"㈥",
		"㈦",
		"㈧",
		"㈨",
		"㈩",
		"⑴",
		"⑵",
		"⑶",
		"⑷",
		"⑸",
		"⑹",
		"⑺",
		"⑻",
		"⑼",
		"⑽",
		"１",
		"２",
		"３",
		"４",
		"５",
		"６",
		"７",
		"８",
		"９",
		"０",
		"{rt1}",
		"{rt2}",
		"{rt3}",
		"{rt4}",
		"{rt5}",
		"{rt6}",
		"{rt7}",
		"{rt8}",
		"臺",
		"寶",
		"會",
		"丫",
		"萬",
		"點",
		"擔",
		"獸",
		"獣",
		"買",
		"賣",
		"棴",
		"戰",
		"塲",
		"絶",
		"坂",
		"咔",
		"墒",
		"業",
		"畢",
		"軍",
		"础",
		"絀",
		"泏",
		"練",
		"唰",
		"鎶",
		"釒",
		"灬",
		"ひ",
		"⊙",
		"〇",
		"○",
		"◎",
		"│",
		"挂机",
		"点[卡心]",
		"[大小]卡",
		"手[工打]",
		"满[及级]",
		"[等升]级",
		"[商店]铺",
		"[新老]店",
		"金[币价]",
		"雕[文纹]",
		"全[程套]",
		"游戏[金币g]",
		"代[打练刷做价]",
		"带[打练刷做价]",
		"dai[打练刷做价]",
		"[买卖售出购要收]金",
		"[买卖售出购要收]g",
		"[买卖售收购要]卡",
		"散[买卖售购]",
		"[拆分]卖",
		"[拆分]售",
		"[皇冲]冠",
		"[热促]销",
		"[充冲]值",
		"[烧大小]饼",
		"马.*宏",
		"坐骑.*宏",
		"工作室",
		"支付宝",
		"灵魂兽",
		"淘宝",
		"平台",
		"全职业",
		"灰皮穆山兽",
		"黑暗之星的灵爪飞鹰",
		"高阶督军",
		"原祖争斗者",
		"战网",
		"点数",
		"5173",
		"[加q]q",
		"yy",
		"rmb",
		"[万w]g",
		"tb",
		"taobao",
		"[~-～]60",
		"[~-～]80",
		"[~-～]85",
		"[~-～]90",
		"[~-～]100",
		"1级",
		"60级",
		"80级",
		"90级",
		"100级",
	},
	["WhiteList"] = {
	},
	["BlackList"] = {
		"86410866",
		"24267225",
		'松波丽',
		'只要2元',
		'十月魔兽',
		'神手网络',
		'小宝魔兽',
		'577153',
		"莉莉兽团",
		"皮皮魔兽",
		"云云魔兽",
		"小羊竞技",
		"牛不白魔兽",
		"神之竞技",
		"玄亚网游",
		"思诺魔兽",
		"莉莉速刷",
		"空空魔兽",
		"琪琪魔兽",
		"皇冠店铺",
		"大头网游",
		"game5808",
		"云云竞技",
		"大宝魔兽",
		"天赐魔兽",
		"华语魔兽",
		"中天网游",
		"68115767",
		"找老公",
		"小七商会",
		"囧小樱",
		"2377802930",
		"556513",
		"568338",
		"41256",
		"东东魔兽",
		"花花兔魔兽",
		"阿咪带刷",
		"一品魔兽",
		"87953180",
		"大甩卖",
		"大减价",
		"打工就位",
		"收金",
		"散卖",
		"97681421",
		"56189",
	},
	["ShieldPlayers"] = {
	},
}
