local _, ns = ...

ns.localization = {}

ns.localization.profile = "Character-specific settings"
ns.localization.profileTooltip = "Switch between a profile that applies to all characters and one that is unique to this character."
ns.localization.credits = "致谢"
ns.localization.install = "安装"
ns.localization.needReload = "你需要重载界面来应用改变。"
ns.localization.needReloadPopup = "你需要重载界面来应用改变。\n\n你想现在就重载界面么？"
ns.localization.requiresReload = "改变这个选项需要重载界面来生效。"
ns.localization.reload = "重载界面"
ns.localization.resetData = "移除数据"
ns.localization.resetDataTooltip = "移除所有保存的数据，例如你的角色有多少金币。"
ns.localization.resetOptions = "移除保存的选项。"
ns.localization.resetOptionsTooltip = "移除所有保存的选项，重置为默认值。"
ns.localization.resetCharBox = "移除这个角色下的所有数据："
ns.localization.layoutText = "使用下面的按钮来转换到另一种界面布局。\n你也可以使用命令行'/freeui dps' 或者 '/freeui heal'"
ns.localization.notificationPreviewText = "这是一个通知示例。"
ns.localization.author = "FreeUI by Haleth on wowinterface.com"
ns.localization.authorSubText = "Lightsword @ Argent Dawn - EU"

ns.localization.general = "综合"
ns.localization.generalSubText = "这些选项控制这个界面的大部分通用设置。"
ns.localization.generalFeatures = "特性"
ns.localization.generalMisc = "其他"
ns.localization.generalbuffreminder = "增益提醒"
ns.localization.generalbuffreminderTooltip = "在战斗中显示你缺失的重要增益。"
ns.localization.generalbuffTracker = "增益追踪"
ns.localization.generalbuffTrackerTooltip = "在屏幕当中偏下的位置对特定的职业显示对应的重要增益。"
ns.localization.generalcombatText = "Combat text"
ns.localization.generalcombatTextTooltip = "Show incoming damage and healing near the player frame."
ns.localization.generalhelmcloakbuttons = "头盔/披风显示隐藏按钮"
ns.localization.generalhelmcloakbuttonsTooltip = "Allows you to toggle Helm/Cloak display from the character frame."
ns.localization.generalinterrupt = "打断提示"
ns.localization.generalinterruptTooltip = "Announce your interrupts when in a raid group or arena, and/or under the circumstances below."
ns.localization.generalinterrupt_party = "小队"
ns.localization.generalinterrupt_partyTooltip = "启用打断提示当你在5人小队和场景战役时（场景战役只有在勾选了副本选项时才会生效）。"
ns.localization.generalinterrupt_bgs = "战场"
ns.localization.generalinterrupt_bgsTooltip = "启用打断提示当你在战场时。"
ns.localization.generalinterrupt_lfg = "副本"
ns.localization.generalinterrupt_lfgTooltip = "启用打断提示当你在副本队伍时。"
ns.localization.generalinterrupt_outdoors = "野外"
ns.localization.generalinterrupt_outdoorsTooltip = "启用打断提示当你不在副本时。"
ns.localization.generalmailButton = "邮件收取按钮"
ns.localization.generalmailButtonTooltip = "在邮件界面添加一个按钮来一键收取所有邮件。"
ns.localization.generalnameplates = "姓名板"
ns.localization.generalnameplatesTooltip = "美化默认姓名板外观。禁用这个选项如果你想使用另外的姓名板插件。"
ns.localization.generalrareAlert = "稀有提醒"
ns.localization.generalrareAlertTooltip = "当在潘达利亚发现稀有时显示一个提醒，小地图上有具体位置。"
ns.localization.generalrareAlert_playSound = "播放声音"
ns.localization.generalthreatMeter = "仇恨计量"
ns.localization.generalthreatMeterTooltip = "在目标框体上添加一个仇恨计量条，当你是坦克时显示第二仇恨的名字和仇恨量，当你是输出时显示你和坦克的仇恨对比。"
ns.localization.generaluiScaleAuto = "强制优化界面缩放"
ns.localization.generaluiScaleAutoTooltip = "自动为你的分辨率使用最优化的界面缩放。"
ns.localization.generalundressButton = "脱衣按钮"
ns.localization.generalundressButtonTooltip = "在试装界面添加一个脱衣按钮。当你试穿内衣或胸甲时会很有用。"

ns.localization.appearance = "外观"
ns.localization.appearanceSubText = "改变这个界面一些部分的外观。"
ns.localization.appearanceColours = "颜色"
ns.localization.appearanceFonts = "字体"
ns.localization.appearanceuseCustomColour = "自定义颜色方案"选择你喜欢的颜色来代替界面中默认的职业颜色。
ns.localization.appearanceuseCustomColourTooltip = "Use a colour of your choice throughout the UI, instead of your class's colour.\n\nClick the square to the right to set the colour."
ns.localization.appearancechooseColour = "Choose..."
ns.localization.appearancefontUseAlternativeFont = "使用备选字体"
ns.localization.appearancefontUseAlternativeFontTooltip = "使用聊天框的字体来替换界面默认的像素字体。"
ns.localization.appearancefontSizeNormal = "普通字体"
ns.localization.appearancefontSizeLarge = "大号字体"
ns.localization.appearancefontOutline = "字体描边"
ns.localization.appearancefontOutlineMonochrome = "像素化描边"
ns.localization.appearancefontShadow = "字体阴影"
ns.localization.appearancesampleText = "示例文字"

ns.localization.automation = "便利功能"
ns.localization.automationSubText = "With these features, the UI can perform common tasks automatically."
ns.localization.automationautoAccept = "Accept invites from friends and guild members"
ns.localization.automationautoRepair = "Repair items"
ns.localization.automationautoRepair_guild = "Use guild funds when available"
ns.localization.automationautoRoll = "Roll disenchant or greed on BoE uncommon items"
ns.localization.automationautoRoll_maxLevel = "Only at max level"
ns.localization.automationautoSell = "Sell junk"
ns.localization.automationautoSellTooltip = "Automatically sell grey quality items to vendors, unless they are used in an equipment set."
ns.localization.automationquestRewardHighlight = "Quest reward highlighting"
ns.localization.automationquestRewardHighlightTooltip = "When turning in a quest, highlight the quest reward with the highest vendor sell price."
ns.localization.automationautoSetRole = "Skip unnecessary role poll popups"
ns.localization.automationautoSetRoleTooltip = "Skip the role poll popup if your role is already set or you are playing a pure dps class."
ns.localization.automationautoSetRole_useSpec = "Set role based on current specialization"
ns.localization.automationautoSetRole_useSpecTooltip = "Always attempt to set your role automatically based on your spec, never showing the popup."
ns.localization.automationautoSetRole_verbose = "Verbose mode"
ns.localization.automationautoSetRole_verboseTooltip = "Enable to be informed of what happens when the popup is skipped."

ns.localization.actionbars = "动作条"
ns.localization.actionbarsSubText = "These options are specific to the action bars and their buttons."
ns.localization.actionbarsenable = "Enable"
ns.localization.actionbarsenableTooltip = "Disable this option if you want to use another action bars addon."
ns.localization.actionbarsenableStyle = "Enable button style"
ns.localization.actionbarsenableStyleTooltip = "You may need to disable this option to ensure compatibility with other action bars addons."
ns.localization.actionbarshotkey = "Show key bindings on buttons"
ns.localization.actionbarsrightbars_mouseover = "Show right action bars on mouseover"

ns.localization.bags = "背包"
ns.localization.bagsSubText = "Toggle and customize the all-in-one bag."
ns.localization.bagssize = "Bag size"
ns.localization.bagsenable = "Enable"
ns.localization.bagsenableTooltip = "Disable this option if you want to use another bag addon."
ns.localization.bagsslotsShowAlways = "Always show item slots"
ns.localization.bagsslotsShowAlwaysTooltip = "Enable to show the border of empty bag slots even when not moving any items."

ns.localization.menubar = "菜单条"
ns.localization.menubarSubText = "The menu bar is the panel at the bottom of the screen. Moving your mouse over it reveals additional functionality and information."
ns.localization.menubarenable = "Enable"
ns.localization.menubarenableButtons = "Enable buttons"
ns.localization.menubarenableButtonsTooltip = "Show buttons on the menu bar."
ns.localization.menubarbuttons_mouseover = "Show buttons on mouseover"
ns.localization.menubarbuttons_mouseoverTooltip = "Only show the buttons when moving the cursor over the menu bar."

ns.localization.notifications = "通知功能"
ns.localization.notificationsSubText = "These options let you choose when and how the UI should show notifications."
ns.localization.notificationsWhen = "When"
ns.localization.notificationsHow = "How"
ns.localization.notificationsPreview = "Preview"
ns.localization.notificationsenable = "Enable"
ns.localization.notificationsenableTooltip = "Allow notifications to be shown. A banner will appear at the top of the UI. Clicking it with either mouse button dismisses the notifications. Clicking it with the left button can also perform an action, such as showing the calendar."
ns.localization.notificationsplaySounds = "Play sounds"
ns.localization.notificationsplaySoundsTooltip = "Play a sound when a notification is shown."
ns.localization.notificationsanimations = "Animations"
ns.localization.notificationsanimationsTooltip = "Animate the banner when it is shown or hidden."
ns.localization.notificationstimeShown = "Time shown"
ns.localization.notificationscheckEvents = "Calendar events"
ns.localization.notificationscheckEventsTooltip = "Show a notification when you have pending calendar events."
ns.localization.notificationscheckGuildEvents = "Guild events"
ns.localization.notificationscheckGuildEventsTooltip = "Show a notification when you have pending guild events. These events do not appear on your calendar button by default and are easily missed."
ns.localization.notificationscheckMail = "Mail"
ns.localization.notificationscheckMailTooltip = "Show a notification when you have new mail."
ns.localization.notificationscheckBagsFull = "Bags full"
ns.localization.notificationscheckBagsFullTooltip = "Show a notification when your bags are full."

ns.localization.unitframes = "Unit frames"
ns.localization.unitframesSubText = "These options control most of the options for the unit frames. If you want to move the unit frames easily, install oUF_MovableFrames."
ns.localization.unitframesenable = "Enable"
ns.localization.unitframesenableTooltip = "Disable this option if you want to use another unit frames addon."
ns.localization.unitframesautoPosition = "Automatically position"
ns.localization.unitframesautoPositionTooltip = "Position the unit frames automatically based on screen resolution. Disable if you want to manually position them in the options file."
ns.localization.unitframesenableGroup = "Party/Raid frames"
ns.localization.unitframesenableGroupTooltip = "Uncheck if you want to use another addon for party and raid frames."
ns.localization.unitframeslimitRaidSize = "Limit raid size"
ns.localization.unitframeslimitRaidSizeTooltip = "Check to show a maximum of 25 players in a raid group."
ns.localization.unitframespartyNameAlways = "Always show group member names"
ns.localization.unitframespartyNameAlwaysTooltip = "Check to show group member names in the dps/tank layout."
ns.localization.unitframescastbarSeparate = "Player castbar as separate bar"
ns.localization.unitframescastbarSeparateTooltip = "When this option is disabled, the player cast bar is embedded in the player frame."
ns.localization.unitframescastbarSeparateOnlyCasters = "Only for caster classes"
ns.localization.unitframescastbarSeparateOnlyCastersTooltip = "Check to only use the separate cast bar as a Mage, Priest, or Warlock."
ns.localization.unitframesabsorb = "吸收量"
ns.localization.unitframesabsorbTooltip = "Shows absorb amounts as well as an over-absorb glow on unit frames."
ns.localization.unitframestargettarget = "Target of Target"
ns.localization.unitframestargettargetTooltip = "Add a Target of Target frame above the target frame."
ns.localization.unitframeshealerClasscolours = "Always use class colours"
ns.localization.unitframeshealerClasscoloursTooltip = "Enable to use class colours rather than gradient in the healer layout."
ns.localization.unitframespvp = "PVP 图标"
ns.localization.unitframespvpTooltip = "在玩家框体显示一个红色的PVP图标。"
ns.localization.unitframesquestIcon = "任务图标"
ns.localization.unitframesquestIconTooltip = "显示任务图标在重要任务NPC的框体。"

ns.localization.unitframesstatusIndicator = "状态指示"
ns.localization.unitframesstatusIndicatorTooltip = "在玩家框体显示休息或战斗状态。"
ns.localization.unitframesstatusIndicatorCombat = "战斗状态"
ns.localization.unitframesstatusIndicatorCombatTooltip = "在玩家框体显示战斗状态。如果禁用，则只显示休息状态。"

ns.localization.unitframesenableArena = "竞技场/扛旗者框体"
ns.localization.unitframesenableArenaTooltip = "打开竞技场敌对目标和战场扛旗者的框体。"

ns.localization.tooltip = "鼠标信息"
ns.localization.tooltipSubText = "调整鼠标信息的外观和功能。"
ns.localization.tooltipanchorCursor = "跟随鼠标"
ns.localization.tooltipguildrank = "公会阶级"
ns.localization.tooltiptitle = "玩家头衔"

ns.localization.classmod = "职业特定"
ns.localization.classmodSubText = "这些选项允许你开关职业特定的模块。"

local classes = UnitSex("player") == 2 and LOCALIZED_CLASS_NAMES_MALE or LOCALIZED_CLASS_NAMES_FEMALE

for class, localized in pairs(classes) do
	ns.localization["classmod"..strlower(class)] = localized
end

ns.localization.classmoddeathknight = ns.localization.classmoddeathknight..":|cffffffff 符文"
ns.localization.classmoddruidMana = ns.localization.classmoddruid..":|cffffffff Shapeshift mana bar"
ns.localization.classmoddruidEclipse = ns.localization.classmoddruid..":|cffffffff Eclipse bar"
ns.localization.classmodmage = ns.localization.classmodmage..":|cffffffff Rune of Power tracker"
ns.localization.classmodmonk = ns.localization.classmodmonk..":|cffffffff Chi and Stagger tracker"
ns.localization.classmodpaladinHP = ns.localization.classmodpaladin..":|cffffffff Holy Power tracker"
ns.localization.classmodpaladinRF = ns.localization.classmodpaladin..":|cffffffff Righteous Fury reminder"
ns.localization.classmodpriest = ns.localization.classmodpriest..":|cffffffff Shadow orb tracker"
ns.localization.classmodwarlock = ns.localization.classmodwarlock..":|cffffffff Specialization bars"

ns.localization.credits = "Credits"
ns.localization.thankYou = "Thank you:"
ns.localization.alza = "For AlzaUI, which once formed the basis for FreeUI"
ns.localization.haste = "For the oUF framework, the foundation of the unit frames in this UI"
ns.localization.tukz = "For allowing the use of his code, and collaboration in UI development"
ns.localization.zork = "For rActionBarStyler, rActionButtonStyler, and rBuffFrameStyler"
ns.localization.others = "as well as..."